export function MyEmailSignature(name, role, email, phone) {
    if (phone) {
        return `<table style="font-family: Georgia;"><tbody><tr><td style="vertical-align: top"><table><tbody><tr><td>
        <a href="https://www.heavyconnect.com/"><img src="https://6118397.fs1.hubspotusercontent-na1.net/hubfs/6118397/hc-icon-white-bg-blue%20-%20Copy-modified.png" role="presentation" width="80" /></a></td></tr><tr><td height="30"></td></tr><tr><td style="text-align: center">
        <table style="display: inline-block; vertical-align: -webkit-baseline-middle;"><tbody><tr style="text-align: center;">
            <td><a href="https://twitter.com/HeavyConnected" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/twitter-icon-2x.png" alt="twitter" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td>
            <td><a href="https://www.linkedin.com/company/heavyconnect/" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/linkedin-icon-2x.png" alt="linkedin" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td>
            <td><a href="https://www.instagram.com/heavyconnect/" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/instagram-icon-2x.png" alt="instagram" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td></tr></tbody></table></td></tr></tbody>
        </table></td><td width="46" style="min-width: 24px"><div></div></td>
        <td style="padding: 0px; vertical-align: middle">
            <h2 style="font-size: 18px; margin: 0px; color: rgb(0, 0, 0); font-weight: 600;"><span>${name}</span></h2>
            <p style="margin: 0px; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"><span>${role}</span></p>
            <p style="margin: 0px; font-weight: 500; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"><span>HeavyConnect</span></p>
            <table cellpadding="0" cellspacing="0" style="width: 100%; vertical-align: -webkit-baseline-middle;">
                <tbody><tr><td height="16"></td></tr><tr><td color="#2A63B2" direction="horizontal" width="auto" height="1" style="width: 100%; border-bottom: 1px solid rgb(42, 99, 178); border-left: none; display: block;"></td></tr><tr><td height="16"></td></tr></tbody>
            </table>
            <table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody>
                <tr height="25" style="vertical-align: middle"><td width="30" style="vertical-align: middle"><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td style="vertical-align: bottom;"><span color="#2A63B2" width="11" style="display: inline-block; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png" color="#2A63B2" alt="emailAddress" width="13" style="display: block; background-color: rgb(42, 99, 178);"/></span></td></tr></tbody></table></td><td style="padding: 0px"><a href="mailto:${email}" color="#000000" style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"><span>${email}</span></a></td></tr>
                <tr height="25" style="vertical-align: middle"><td width="30" style="vertical-align: middle"><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td style="vertical-align: bottom;"><span color="#2A63B2" width="11" style="display: inline-block; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png" color="#2A63B2" alt="website" width="13" style=" display: block; background-color: rgb(42, 99, 178);"/></span></td></tr></tbody></table></td><td style="padding: 0px"><a href="https://www.heavyconnect.com/" color="#000000" style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"><span>HeavyConnect.com</span></a></td></tr>
                <tr><td style="vertical-align: bottom;"><span color="#2A63B2" width="11" class="contact-info__IconWrapper-sc-mmkjr6-1 bglVXe" style="display: inline-block; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png" color="#2A63B2" alt="mobilePhone" width="13" class="contact-info__ContactLabelIcon-sc-mmkjr6-0 cnkwri" style="display: block; background-color: rgb(42, 99, 178);"></span></td><td style="padding: 0px; color: rgb(0, 0, 0);"><a href="tel:${phone}" color="#000000" class="contact-info__ExternalLink-sc-mmkjr6-2 ibLXSU" style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"><span>${phone}</span></a></td></tr></tbody>
            </table>
            <table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td height="30"></td></tr></tbody></table><span style="max-width: 1080px;"><a style="display: inline-block; color: rgb(0, 0, 0); font-weight: 600; text-align: center; line-height: 16px; font-size: 10px;">The information in this message and any attachments is confidential and may be privileged. Access to this email by anyone other than the intended recipient is not authorized. If you are not the intended recipient, disclosure, copying or use of the contents of this email is prohibited. If you are not the intended recipient, please notify the sender immediately by calling the sender or by sending an email to the sender's address set forth above, and please destroy the email you received in error.</a></span><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td height="30"></td></tr></tbody></table>
        </td></tr></tbody></table>`;
    }

    return `<table style="font-family: Georgia;"><tbody><tr><td style="vertical-align: top"><table><tbody><tr><td>
        <a href="https://www.heavyconnect.com/"><img src="https://6118397.fs1.hubspotusercontent-na1.net/hubfs/6118397/hc-icon-white-bg-blue%20-%20Copy-modified.png" role="presentation" width="80" /></a></td></tr><tr><td height="30"></td></tr><tr><td style="text-align: center">
        <table style="display: inline-block; vertical-align: -webkit-baseline-middle;"><tbody><tr style="text-align: center;">
            <td><a href="https://twitter.com/HeavyConnected" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/twitter-icon-2x.png" alt="twitter" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td>
            <td><a href="https://www.linkedin.com/company/heavyconnect/" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/linkedin-icon-2x.png" alt="linkedin" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td>
            <td><a href="https://www.instagram.com/heavyconnect/" color="#2A63B2" style="display: inline-block; padding: 0px; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/instagram-icon-2x.png" alt="instagram" color="#2A63B2" height="24" style="background-color: rgb(42, 99, 178); max-width: 135px; display: block;" /></a></td><td width="5"><div></div></td></tr></tbody></table></td></tr></tbody>
        </table></td><td width="46" style="min-width: 24px"><div></div></td>
        <td style="padding: 0px; vertical-align: middle">
            <h2 style="font-size: 18px; margin: 0px; color: rgb(0, 0, 0); font-weight: 600;"><span>${name}</span></h2>
            <p style="margin: 0px; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"><span>${role}</span></p>
            <p style="margin: 0px; font-weight: 500; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"><span>HeavyConnect</span></p>
            <table cellpadding="0" cellspacing="0" style="width: 100%; vertical-align: -webkit-baseline-middle;">
                <tbody><tr><td height="16"></td></tr><tr><td color="#2A63B2" direction="horizontal" width="auto" height="1" style="width: 100%; border-bottom: 1px solid rgb(42, 99, 178); border-left: none; display: block;"></td></tr><tr><td height="16"></td></tr></tbody>
            </table>
            <table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody>
                <tr height="25" style="vertical-align: middle"><td width="30" style="vertical-align: middle"><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td style="vertical-align: bottom;"><span color="#2A63B2" width="11" style="display: inline-block; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png" color="#2A63B2" alt="emailAddress" width="13" style="display: block; background-color: rgb(42, 99, 178);"/></span></td></tr></tbody></table></td><td style="padding: 0px"><a href="mailto:${email}" color="#000000" style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"><span>${email}</span></a></td></tr>
                <tr height="25" style="vertical-align: middle"><td width="30" style="vertical-align: middle"><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td style="vertical-align: bottom;"><span color="#2A63B2" width="11" style="display: inline-block; background-color: rgb(42, 99, 178);"><img src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png" color="#2A63B2" alt="website" width="13" style=" display: block; background-color: rgb(42, 99, 178);"/></span></td></tr></tbody></table></td><td style="padding: 0px"><a href="https://www.heavyconnect.com/" color="#000000" style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"><span>HeavyConnect.com</span></a></td></tr></tbody>
            </table>
            <table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td height="30"></td></tr></tbody></table><span style="max-width: 1080px;"><a style="display: inline-block; color: rgb(0, 0, 0); font-weight: 600; text-align: center; line-height: 16px; font-size: 10px;">The information in this message and any attachments is confidential and may be privileged. Access to this email by anyone other than the intended recipient is not authorized. If you are not the intended recipient, disclosure, copying or use of the contents of this email is prohibited. If you are not the intended recipient, please notify the sender immediately by calling the sender or by sending an email to the sender's address set forth above, and please destroy the email you received in error.</a></span><table cellpadding="0" cellspacing="0" style="vertical-align: -webkit-baseline-middle;"><tbody><tr><td height="30"></td></tr></tbody></table>
        </td></tr></tbody></table>`;
}
